name: sermacs-2024
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - matplotlib
  - numpy
  - jupyterlab
  - plotly
  - nglview
  - rdkit
  - openbabel
  - mdanalysis
  - vina
  - ipywidgets>8
  - prolif
  - pip:
    - pdb2pqr
    - meeko
    - py3Dmol